-- ============================================================
-- HorusWebsite migration: Supabase (PostgreSQL)
-- Выполнить целиком в Supabase Dashboard -> SQL Editor
-- ============================================================

create table if not exists users (
  id               bigint generated by default as identity primary key,
  login            text not null,
  email            text not null,
  pass_hash        text not null,
  uid              text not null,
  hwid             text,
  created_at       timestamptz not null default now(),
  last_hwid_reset  timestamptz
);

create unique index if not exists users_uid_idx   on users (uid);
create unique index if not exists users_login_idx on users (lower(login));
create unique index if not exists users_email_idx on users (lower(email));

create table if not exists sessions (
  token      text primary key,
  user_id    bigint not null,
  created_at timestamptz not null,
  expires_at timestamptz not null
);

create table if not exists subs (
  id           bigint generated by default as identity primary key,
  user_id      bigint not null,
  plan         text not null,
  status       text not null default 'active',
  source       text not null,
  licence_key  text,
  purchased_at timestamptz not null,
  expires_at   timestamptz
);

create index if not exists subs_user_idx on subs (user_id);

create table if not exists hw_resets (
  id       bigint generated by default as identity primary key,
  user_id  bigint not null,
  reset_at timestamptz not null
);

create index if not exists hw_resets_user_idx on hw_resets (user_id);

create table if not exists promo_codes (
  id         bigint generated by default as identity primary key,
  code       text not null unique,
  plan       text not null,
  max_uses   integer not null default 1,
  days       integer not null default 0,
  used_count integer not null default 0,
  created_by bigint not null,
  created_at timestamptz not null
);

create table if not exists orders (
  id         bigint generated by default as identity primary key,
  user_id    bigint,
  plan       text not null,
  status     text not null default 'pending',
  created_at timestamptz not null
);

create table if not exists tickets (
  id         bigint generated by default as identity primary key,
  user_id    bigint,
  type       text not null,
  subject    text not null,
  message    text not null,
  created_at timestamptz not null
);

create table if not exists site_cfg (
  key   text primary key,
  value text not null
);

insert into site_cfg (key, value) values
  ('discord_members', '1421'),
  ('telegram_members', '987'),
  ('discord_url', 'https://discord.gg/sGjbnrdBfw'),
  ('telegram_url', 'https://t.me/HorusClVS'),
  ('purchase_note', 'Оплата скоро появится. Для покупки напишите в Discord или Telegram.')
on conflict (key) do nothing;

-- ПОСЛЕ импорта данных из SQLite выполните supabase/fix_sequences.sql,
-- чтобы identity-последовательности учитывали импортированные id.

-- Скидочные промокоды (выполнить в SQL Editor, если таблицы ещё нет)
-- Миграция: скидочные промокоды
-- Выполнить ОДИН РАЗ: Supabase Dashboard -> SQL Editor -> New query -> Run

create table if not exists discount_promos (
  id bigint generated always as identity primary key,
  code text not null unique,
  discount int not null check (discount between 1 and 99),
  plans jsonb not null default '[]'::jsonb,
  created_by text not null default 'Howill_',
  uses int not null default 0,
  created_at timestamptz not null default now()
);

alter table orders add column if not exists amount numeric;
alter table orders add column if not exists promo_code text;
